---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mimz9857/public_html/mfin
    - /bin/cp -R * $DEPLOYPATH
    # Tambahkan '|| true' agar jika .htaccess tidak ada, proses tidak error/nyangkut
    - /bin/cp .htaccess $DEPLOYPATH || true
    # Tambahkan echo untuk memberikan sinyal sukses ke cPanel
    - /bin/echo "Deployment Berhasil"